# Generated by Django 4.1.6 on 2023-05-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('dsg', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=25, null=True)),
            ],
        ),
    ]
